# Generated by Django 4.2.3 on 2023-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default_images/avatar.png', upload_to='owner_profile/'),
        ),
    ]
