# Generated by Django 4.2.3 on 2023-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default_images/avatar.png', upload_to='media/owner_profile/'),
        ),
    ]
