# Generated by Django 4.2.3 on 2023-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_id", models.CharField(max_length=32)),
                ("blog_person_id", models.IntegerField(max_length=32)),
                ("blog_title", models.CharField(max_length=256)),
                ("blog_content", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=64)),
                ("password", models.CharField(default="", max_length=64)),
                ("name", models.CharField(default="", max_length=64)),
                ("github_id", models.CharField(default="", max_length=32)),
            ],
        ),
    ]
