# Generated by Django 4.2.3 on 2023-07-20 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_blog_blog_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="writesomething",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
