# Generated by Django 4.2.3 on 2023-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
