# Generated by Django 4.2.3 on 2023-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skills_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='days',
            field=models.ManyToManyField(related_name='skills_days', to='skills.weekdays'),
        ),
    ]
