# Generated by Django 4.2.3 on 2023-07-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_weekdays_skills_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='days',
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
    ]
