# Generated by Django 4.2.3 on 2023-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='title2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
