# Generated by Django 4.2.3 on 2023-07-18 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0008_skills_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='like',
            field=models.ManyToManyField(related_name='skills_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
