# Generated by Django 4.2.3 on 2023-07-20 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0009_skills_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(max_length=5)),
                ('user', models.ManyToManyField(related_name='rate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='rating',
            field=models.ManyToManyField(related_name='skills_rating', to='skills.rate'),
        ),
    ]
