# Generated by Django 4.2.3 on 2023-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_rate_skills_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
