# Generated by Django 4.2.3 on 2023-07-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_alter_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='rate',
        ),
    ]
