# Generated by Django 4.2.3 on 2023-07-20 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0012_remove_skills_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='title2',
        ),
        migrations.AlterField(
            model_name='skills',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
