# Generated by Django 4.2.3 on 2023-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_remove_skills_title2_alter_skills_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills_rating', to='skills.rate'),
        ),
    ]
