# Generated by Django 4.2.3 on 2023-07-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_alter_skills_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
    ]
